Repository ISIS3510-202510-G21/Kotlin-G21, pull requests merged in 2025-04, with the labels that each got.

#44 32 fix rendering issues in home screen
  .idea/appInsightsSettings.xml
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/java/com/isis3510/growhub/Repository/CategoryRepository.kt
  app/src/main/java/com/isis3510/growhub/local/data/CategoryDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/CategoryEntity.kt
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Category.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Event.kt
  app/src/main/java/com/isis3510/growhub/model/objects/location.kt
  app/src/main/java/com/isis3510/growhub/utils/SingleLiveEvent.kt
  app/src/main/java/com/isis3510/growhub/view/home/CategoriesView.kt
  app/src/main/java/com/isis3510/growhub/view/home/EventsView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/home/TopBarView.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/BottomNavBar.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CategoriesViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/LocationViewModel.kt
  gradle/libs.versions.toml
Labels: bug, enhancement, quality attribute

#45 38 implement the search events view
  app/build.gradle.kts
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Event.kt
  app/src/main/java/com/isis3510/growhub/service/GeminiApiService.kt
  app/src/main/java/com/isis3510/growhub/utils/ConnectivityObserver.kt
  app/src/main/java/com/isis3510/growhub/utils/Converters.kt
  app/src/main/java/com/isis3510/growhub/view/chatbot/ChatbotView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SearchEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulRegistrationView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/home/TopBarView.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ChatbotViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ConnectivityViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MapViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SearchEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SuccessfulRegistrationViewModel.kt
  app/src/main/res/drawable-mdpi/chatbot.png
Labels: bug, enhancement, quality attribute

#47 46 update myevents profile and chatbot for interaction and ecns
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/utils/CacheObjects.kt
  app/src/main/java/com/isis3510/growhub/view/chatbot/ChatbotView.kt
  app/src/main/java/com/isis3510/growhub/view/dummy/Dummy.kt
  app/src/main/java/com/isis3510/growhub/view/events/MyEventsView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SearchEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulRegistrationView.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/view/profile/ProfileView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MyEventsViewModel.kt
Labels: enhancement, quality attribute

#52 46 update myevents profile and chatbot for interaction and ecns
  .idea/appInsightsSettings.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isis3510/growhub/Repository/EventRepository.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventEntity.kt
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Event.kt
  app/src/main/java/com/isis3510/growhub/view/chatbot/ChatbotView.kt
  app/src/main/java/com/isis3510/growhub/view/events/MyEventsView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SearchEventView.kt
  app/src/main/java/com/isis3510/growhub/view/home/EventsView.kt
  app/src/main/java/com/isis3510/growhub/view/profile/ProfileView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MapViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MyEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SearchEventViewModel.kt
Labels: enhancement, quality attribute

#53 33 incorporate multithreading for map screen view
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  app/src/main/java/com/isis3510/growhub/local/data/EventEntity.kt
  app/src/main/java/com/isis3510/growhub/local/data/GlobalData.kt
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Event.kt
  app/src/main/java/com/isis3510/growhub/model/objects/MarkerData.kt
  app/src/main/java/com/isis3510/growhub/model/objects/location.kt
  app/src/main/java/com/isis3510/growhub/view/events/SearchEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulRegistrationView.kt
  app/src/main/java/com/isis3510/growhub/view/home/EventsView.kt
  app/src/main/java/com/isis3510/growhub/view/map/MapScreen.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MapViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SearchEventViewModel.kt
Labels: enhancement

#54 Develop to Main #1
  .idea/appInsightsSettings.xml
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/isis3510/growhub/MainActivity.kt
  app/src/main/java/com/isis3510/growhub/Repository/CategoryRepository.kt
  app/src/main/java/com/isis3510/growhub/Repository/CreateEventRepository.kt
  app/src/main/java/com/isis3510/growhub/Repository/EventRepository.kt
  app/src/main/java/com/isis3510/growhub/local/data/CategoryDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/CategoryEntity.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventEntity.kt
  app/src/main/java/com/isis3510/growhub/local/data/GlobalData.kt
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Category.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Event.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Location.kt
  app/src/main/java/com/isis3510/growhub/model/objects/MarkerData.kt
  app/src/main/java/com/isis3510/growhub/model/objects/location.kt
  app/src/main/java/com/isis3510/growhub/service/GeminiApiService.kt
  app/src/main/java/com/isis3510/growhub/utils/CacheObjects.kt
  app/src/main/java/com/isis3510/growhub/utils/ConnectivityObserver.kt
  app/src/main/java/com/isis3510/growhub/utils/Converters.kt
  app/src/main/java/com/isis3510/growhub/utils/SingleLiveEvent.kt
  app/src/main/java/com/isis3510/growhub/view/chatbot/ChatbotView.kt
  app/src/main/java/com/isis3510/growhub/view/dummy/Dummy.kt
  app/src/main/java/com/isis3510/growhub/view/events/MyEventsView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SearchEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulRegistrationView.kt
  app/src/main/java/com/isis3510/growhub/view/home/CategoriesView.kt
  app/src/main/java/com/isis3510/growhub/view/home/EventsView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/home/TopBarView.kt
  app/src/main/java/com/isis3510/growhub/view/map/MapScreen.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/BottomNavBar.kt
  app/src/main/java/com/isis3510/growhub/view/profile/ProfileView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CategoriesViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ChatbotViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ConnectivityViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/LocationViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MapViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MyEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SearchEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SuccessfulRegistrationViewModel.kt
  app/src/main/res/drawable-mdpi/chatbot.png
  gradle/libs.versions.toml
Labels: enhancement

#51 43 implementation of eventdetail
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/isis3510/growhub/Repository/CreateEventRepository.kt
  app/src/main/java/com/isis3510/growhub/model/AuthPreferences.kt
  app/src/main/java/com/isis3510/growhub/model/objects/AuthUiState.kt
  app/src/main/java/com/isis3510/growhub/model/objects/location.kt
  app/src/main/java/com/isis3510/growhub/model/offline/NetworkUtils.kt
  app/src/main/java/com/isis3510/growhub/model/offline/OfflineEvent.kt
  app/src/main/java/com/isis3510/growhub/model/offline/OfflineEventManager.kt
  app/src/main/java/com/isis3510/growhub/view/auth/InterestsScreen.kt
  app/src/main/java/com/isis3510/growhub/view/auth/LoginScreen.kt
  app/src/main/java/com/isis3510/growhub/view/auth/RegisterScreen.kt
  app/src/main/java/com/isis3510/growhub/view/events/CreateEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/EventDetailView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/BottomNavBar.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/AuthViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModelFactory.kt
  app/src/main/res/drawable/ic_category.png
  app/src/main/res/drawable/ic_check.png
  app/src/main/res/drawable/ic_money.png
  app/src/main/res/drawable/ic_pin.png
Labels: enhancement
