Repository ISIS3510-202510-G21/Kotlin-G21, pull requests merged in 2025-05, with the labels that each got.

#49 41 implement cachingmt in a current feature
  app/src/main/java/com/isis3510/growhub/model/RegistrationCache.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/objects/AppUser.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Event.kt
  app/src/main/java/com/isis3510/growhub/view/auth/InterestsScreen.kt
  app/src/main/java/com/isis3510/growhub/view/auth/LoginScreen.kt
  app/src/main/java/com/isis3510/growhub/view/auth/RegisterScreen.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/BottomNavBar.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/AuthViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModelFactory.kt
  app/src/main/res/drawable/ic_interest_default.png
Labels: enhancement, quality attribute

#58 Fixing issues
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  app/src/main/java/com/isis3510/growhub/view/auth/InterestsScreen.kt
  app/src/main/java/com/isis3510/growhub/view/auth/LoginScreen.kt
  app/src/main/java/com/isis3510/growhub/view/auth/RegisterScreen.kt
  app/src/main/java/com/isis3510/growhub/view/events/EventDetailView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/EventDetailViewModel.kt
Labels: bug, enhancement

#61 60 add multithreading to current features
  app/src/main/java/com/isis3510/growhub/Repository/CategoryRepository.kt
  app/src/main/java/com/isis3510/growhub/Repository/EventRepository.kt
  app/src/main/java/com/isis3510/growhub/Repository/ProfileRepository.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/GlobalData.kt
  app/src/main/java/com/isis3510/growhub/local/data/ProfileDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/ProfileEntity.kt
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Profile.kt
  app/src/main/java/com/isis3510/growhub/view/chatbot/ChatbotView.kt
  app/src/main/java/com/isis3510/growhub/view/events/MyEventsView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SearchEventView.kt
  app/src/main/java/com/isis3510/growhub/view/home/CategoriesView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CategoriesViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ChatbotViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MyEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ProfileViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SearchEventViewModel.kt
Labels: enhancement, quality attribute

#63 Hotfix/home localstorage
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/isis3510/growhub/Repository/EventRepository.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventEntity.kt
  app/src/main/java/com/isis3510/growhub/local/data/GlobalData.kt
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/view/map/MapScreen.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/LocationViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MapViewModel.kt
Labels: bug

#65 62 connect succesfulregistration with createevent and create new attendees screen
  app/src/main/java/com/isis3510/growhub/service/GeminiApiService.kt
  app/src/main/java/com/isis3510/growhub/view/chatbot/ChatbotView.kt
  app/src/main/java/com/isis3510/growhub/view/events/MyEventsView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulRegistrationView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/ChatbotViewModel.kt
Labels: enhancement, quality attribute

#66 better caché
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/isis3510/growhub/model/AuthPreferences.kt
  app/src/main/java/com/isis3510/growhub/view/auth/RegisterScreen.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/AuthViewModel.kt
Labels: enhancement

#70 34 implement and incorporate filters in the home view
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/isis3510/growhub/local/data/ClickQueueManager.kt
  app/src/main/java/com/isis3510/growhub/local/data/GlobalData.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/utils/MapClick.kt
  app/src/main/java/com/isis3510/growhub/view/home/CategoryDetailView.kt
  app/src/main/java/com/isis3510/growhub/view/home/EventsView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/map/MapScreen.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CategoryDetailViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MapViewModel.kt
Labels: enhancement

#71 Develop
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/isis3510/growhub/local/data/ClickQueueManager.kt
  app/src/main/java/com/isis3510/growhub/local/data/GlobalData.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/utils/MapClick.kt
  app/src/main/java/com/isis3510/growhub/view/auth/RegisterScreen.kt
  app/src/main/java/com/isis3510/growhub/view/home/CategoryDetailView.kt
  app/src/main/java/com/isis3510/growhub/view/home/EventsView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/map/MapScreen.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CategoryDetailViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/HomeEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/MapViewModel.kt
Labels: bug, enhancement, quality attribute

#78 77 implement micro optimizations
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  app/src/main/java/com/isis3510/growhub/view/events/EventDetailView.kt
Labels: enhancement

#79 micropops create event
  app/src/main/java/com/isis3510/growhub/view/events/CreateEventView.kt
Labels: enhancement

#82 Micro-optimization done
  app/src/main/java/com/isis3510/growhub/view/home/CategoriesView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/NearbyEventsViewModel.kt
Labels: enhancement, microoptimization

#83 72 implement the attendees view
  app/src/main/java/com/isis3510/growhub/Repository/EventRepository.kt
  app/src/main/java/com/isis3510/growhub/Repository/ProfileRepository.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/ProfileDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/ProfileEntity.kt
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Profile.kt
  app/src/main/java/com/isis3510/growhub/utils/CacheObjects.kt
  app/src/main/java/com/isis3510/growhub/view/attendees/AttendeesView.kt
  app/src/main/java/com/isis3510/growhub/view/events/EventDetailView.kt
  app/src/main/java/com/isis3510/growhub/view/events/MyEventsView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SearchEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulRegistrationView.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/view/profile/ProfileView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/AttendeesViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SearchEventViewModel.kt
Labels: enhancement, quality attribute, microoptimization

#84 31 implement successful creation view
  app/src/main/java/com/isis3510/growhub/Repository/CreateEventRepository.kt
  app/src/main/java/com/isis3510/growhub/model/offline/OfflineEventManager.kt
  app/src/main/java/com/isis3510/growhub/view/events/CreateEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulCreationView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModelFactory.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SuccessfulCreationViewModel.kt
Labels: enhancement, quality attribute

#85 Develop
  .idea/deploymentTargetSelector.xml
  .idea/gradle.xml
  app/src/main/java/com/isis3510/growhub/Repository/CreateEventRepository.kt
  app/src/main/java/com/isis3510/growhub/Repository/EventRepository.kt
  app/src/main/java/com/isis3510/growhub/Repository/ProfileRepository.kt
  app/src/main/java/com/isis3510/growhub/local/data/EventDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/ProfileDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/ProfileEntity.kt
  app/src/main/java/com/isis3510/growhub/local/database/AppLocalDatabase.kt
  app/src/main/java/com/isis3510/growhub/model/facade/FirebaseServicesFacade.kt
  app/src/main/java/com/isis3510/growhub/model/filter/Filter.kt
  app/src/main/java/com/isis3510/growhub/model/objects/Profile.kt
  app/src/main/java/com/isis3510/growhub/model/offline/OfflineEventManager.kt
  app/src/main/java/com/isis3510/growhub/utils/CacheObjects.kt
  app/src/main/java/com/isis3510/growhub/view/attendees/AttendeesView.kt
  app/src/main/java/com/isis3510/growhub/view/events/CreateEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/EventDetailView.kt
  app/src/main/java/com/isis3510/growhub/view/events/MyEventsView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SearchEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulCreationView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulRegistrationView.kt
  app/src/main/java/com/isis3510/growhub/view/home/CategoriesView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/view/profile/ProfileView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/AttendeesViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModelFactory.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/NearbyEventsViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SearchEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SuccessfulCreationViewModel.kt
Labels: enhancement, quality attribute, microoptimization

#86 Create README.md
  README.md
Labels: documentation

#87 73 implement the followersfollowing view
  app/src/main/java/com/isis3510/growhub/Repository/CreateEventRepository.kt
  app/src/main/java/com/isis3510/growhub/Repository/FollowRepository.kt
  app/src/main/java/com/isis3510/growhub/local/data/FollowItemDao.kt
  app/src/main/java/com/isis3510/growhub/local/data/FollowItemEntity.kt
  app/src/main/java/com/isis3510/growhub/local/data/GlobalData.kt
  app/src/main/java/com/isis3510/growhub/local/database/FollowLocalStore.kt
  app/src/main/java/com/isis3510/growhub/model/objects/FollowItem.kt
  app/src/main/java/com/isis3510/growhub/model/offline/OfflineEventManager.kt
  app/src/main/java/com/isis3510/growhub/utils/LocationPermissionHandler.kt
  app/src/main/java/com/isis3510/growhub/view/events/CreateEventView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulCreationView.kt
  app/src/main/java/com/isis3510/growhub/view/events/SuccessfulRegistrationView.kt
  app/src/main/java/com/isis3510/growhub/view/home/Home.kt
  app/src/main/java/com/isis3510/growhub/view/home/TopBarView.kt
  app/src/main/java/com/isis3510/growhub/view/navigation/AppNavGraph.kt
  app/src/main/java/com/isis3510/growhub/view/profile/FollowRow.kt
  app/src/main/java/com/isis3510/growhub/view/profile/FollowersView.kt
  app/src/main/java/com/isis3510/growhub/view/profile/FollowingView.kt
  app/src/main/java/com/isis3510/growhub/view/profile/ProfileView.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/CreateEventViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/FollowViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/LocationViewModel.kt
  app/src/main/java/com/isis3510/growhub/viewmodel/SuccessfulCreationViewModel.kt
Labels: bug, enhancement, quality attribute
